### PR TITLE
add backward compat alias for _Wildcard

### LINKED ISSUE #3580: cannot import name '_Wildcard' from 'dash.dependencies
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**

```
dash                        3.4.0
dash_ag_grid                31.3.1
dash-iconify                0.1.2
dash_mantine_components     2.4.1
dash-pydantic-form          0.18.2
dash-pydantic-utils         0.18.2
```

**Describe the bug**
Our app using dash used to work yesterday on 3.3.0 and fail after a new build on 3.4.0:

```
from dash_pydantic_form import ModelForm  

File "/usr/local/lib/python3.11/site-packages/dash_pydantic_form/__init__.py", line 6, in <module>  
from dash_pydantic_form.fields import fields  

File "/usr/local/lib/python3.11/site-packages/dash_pydantic_form/fields/__init__.py", line 11, in <module>  
from . import all_fields as fields  

File "/usr/local/lib/python3.11/site-packages/dash_pydantic_form/fields/all_fields.py", line 3, in <module>  
from .base_fields import AutocompleteField as Autocomplete  

File "/usr/local/lib/python3.11/site-packages/dash_pydantic_form/fields/base_fields.py", line 20, in <module>  
from dash_pydantic_form import ids as common_ids  

File "/usr/local/lib/python3.11/site-packages/dash_pydantic_form/ids.py", line 3, in <module>  
from dash.dependencies import _Wildcard  

ImportError: cannot import name '_Wildcard' from 'dash.dependencies' (/usr/local/lib/python3.11/site-packages/dash/dependencies.py)  
```

### PR DESCRIPTION
**Pull request by Mr-Neutr0n**
The `_Wildcard` class was renamed to `Wildcard` in Dash 3.4, but some third-party packages (like dash-pydantic-form) still import the old private name. This breaks on upgrade from 3.3 → 3.4 with `ImportError: cannot import name '_Wildcard' from 'dash.dependencies'`.

This adds `_Wildcard = Wildcard` as a one-line alias so those imports keep working.

Fixes #3580

### CODE REVIEW

**Review by T4rk1n — APPROVED** [review]
💃 Thank you
