### ISSUE TITLE
[BUG] Dash 3.0 fails mypy

### ISSUE THREAD

**Issue by gothicVI** [plotly/dash#3226]
With the release of dash 3.0 our CI/CD fails for stuff that used to work.
Here's a minimum working example:
```python
from dash import Dash, dcc, html
from dash.dependencies import Input, Output
from typing import Callable

app = Dash(__name__)

def create_layout() -> html.Div:
    return html.Div([
        dcc.Input(id='input-text', type='text', value='', placeholder='Enter text'),
        html.Div(id='output-text')
    ])  

app.layout = create_layout

# Explicitly cast Input and Output to satisfy mypy
input_component: Input = Input('input-text', 'value')
output_component: Output = Output('output-text', 'children')

@app.callback(output_component, input_component)
def update_output(value: str) -> str:
    return f'You entered: {value}'

if __name__ == '__main__':
    app.run(debug=True, port=9000)
```
running mypy on this file results in:
```bash
$ mypy t.py --strict
t.py:1: error: Skipping analyzing "dash": module is installed, but missing library stubs or py.typed marker  [import-untyped]
t.py:2: error: Skipping analyzing "dash.dependencies": module is installed, but missing library stubs or py.typed marker  [import-untyped]
t.py:2: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
t.py:19: error: Untyped decorator makes function "update_output" untyped  [misc]
Found 3 errors in 1 file (checked 1 source file)
```
which we used to solve by adding `# type: ignore[misc]` to every `callback` call and by adding
```toml
[[tool.mypy.overrides]]
module = [
  "dash.*",
  "dash_ag_grid",
  "dash_bootstrap_components.*",
  "plotly.*",
]
ignore_missing_imports = true
```
to our `pyproject.toml`.

However, when updating to version 3, we get:
```bash
$ mypy --strict t.py 
t.py:8: error: Returning Any from function declared to return "Div"  [no-any-return]
t.py:13: error: Property "layout" defined in "Dash" is read-only  [misc]
t.py:16: error: Call to untyped function "Input" in typed context  [no-untyped-call]
t.py:17: error: Call to untyped function "Output" in typed context  [no-untyped-call]
t.py:19: error: Call to untyped function "callback" in typed context  [no-untyped-call]
t.py:19: note: Error code "no-untyped-call" not covered by "type: ignore" comment
Found 5 errors in 1 file (checked 1 source file)
```
without changing anything else.

This can't be intended behavior, right? How to fix that?

**Comment by T4rk1n** [comment]
I only had trouble with mypy, the typing generation tests were originally designed with mypy but at some point it updated and couldn't find types anymore. There is a `py.typed` file in dash package.

I suggest switching over to `pyright`, that is what is used in vscode and 10x better imo.

**Comment by gothicVI** [comment]
I'll give that a look but we can not simply dump mypy from our code base.
This needs to be fixed not on a linter level because there is something wrong in the code.

**Comment by gothicVI** [comment]
There are several issues with the claimed "typedness" for dash. In  a fresh virtual environment I get:
```bash
$ mypy .
dash-core-components is not a valid Python package name
$ cd dash
mypy: "types.py" shadows library module "types"
note: A user-defined top-level module with name "types" is not supported
$ cd ..
$ pyright 
# see https://gist.github.com/gothicVI/34eb60a2a2f61b02d6a2c50027355a11 for very long output
$ cd dash
$ pyright 
# see https://gist.github.com/gothicVI/b2f30b6cbfbc648909eb3f82c4560c2c for lengthy output
```
which tells me that the packages violates python conventions and is not typed.
@T4rk1n how does that work for you?

**Comment by gvwilson** [comment]
Hi @gothicVI - thanks for filing this issue. We're aware that there's still work to do on Dash typing, and given resources at our end we have to take it in stages. If you would like to post a PR with a handful of the changes you would like to see, we can review that right away, and it will help us figure out how much effort it will be to solve the whole problem. Thanks - @gvwilson

**Comment by gothicVI** [comment]
@gvwilson I didn't mean to revert the release of version 3 but just the commits that break the typing system.

Either way, can you or anyone else confirm that the new version breaks mypy at all?

Independently I've looked into converting the `setup.py` approach to a `pyproject.toml` approach.
However, I can't even build the current project state due to `dash/labextension/dist/dash-jupyterlab.tgz` being required but missing. What's happening here? How does the build process even work?

My attempt at conversion can be found here: https://github.com/gothicVI/dash/commit/ed59db7ff1fc2cefe72e51b4f82ceed7367294fb
I'd start a PR once I'm sure the project can be built at all.

**Comment by gothicVI** [comment]
@gvwilson any news?

**Comment by gvwilson** [comment]
Nothing yet, but I'll be sure to post when there is.

**Comment by gvwilson** [comment]
@gothicVI can you please tell us more about the build issue you're having? when I go through the steps in `CONTRIBUTING.md` on MacOS everything seems to build correctly (though there are currently some failing tests - I'm looking into those). What platform are you on and are any steps breaking _before_ you hit the jupyterlab issue? Separately, can you please create a PR with your pyproject.toml file that _doesn't_ delete the existing `requirements/*` files? We can work on getting that in place in parallel with typing changes. thanks - @gvwilson

**Comment by gothicVI** [comment]
@gvwilson I honestly can no longer reproduce the issue I had but it would fail due to `dash/labextension/dist/dash-jupyterlab.tgz` not existing. Following the same steps though I'm running into issues because `orjson` does not build with python `3.13` even though that should be supported as per the project. The problem here might be that `dash` does not support `3.13` itself.

I'll try again with `3.11`.

**Comment by T4rk1n** [comment]
Investigated the type checkers, I found that mypy doesn't even resolve the html/dcc types that were added while it works fine with pyright/vscode/pycharm.

This error results from that:
```
t.py:8: error: Returning Any from function declared to return "Div"  [no-any-return]
```
It happens that `mypy` can't resolve the `@_explicitize_args` we put in front of the `__init__` of the components and ends up with `Any` instead of the component.

Adding type vars can resolve the return type, but break the init types. Can probably refactor the decorator behavior inside the `__new__` of ComponentMeta.

```
error: Property "layout" defined in "Dash" is read-only  [misc]
```
Has been fixed in 3.0.2 by community PR: #3249 

```
t.py:15: error: Call to untyped function "Input" in typed context  [no-untyped-call]
t.py:15: error: Call to untyped function "Output" in typed context  [no-untyped-call]
```
The dash dependencies will be typed in next dash release by #3259 

```
t.py:15: error: Call to untyped function "callback" in typed context  [no-untyped-call]
```
This can be fixed/silenced with `def callback(...) -> Callable[..., Any]`, also added in #3259, the global `@callback` contains more types for the arguments that should be added in the app one. Maybe a type var can be used, but seems to work well when the function is typed.

**Comment by gothicVI** [comment]
@T4rk1n that looks great. Any change to add `mypy` to the standard CI suite as well? I use `pyright` as well but `mypy` is the de-facto standard as it's the official type checker.

**Comment by T4rk1n** [comment]
> [@T4rk1n](https://github.com/T4rk1n) that looks great. Any change to add `mypy` to the standard CI suite as well? I use `pyright` as well but `mypy` is the de-facto standard as it's the official type checker.

I'll probably add a basic test for mypy to not throw error with a basic app and make sure it resolve the types of the components. But for the rest of the codebase it should run `pyright` as mypy is very slow in comparison for the same kind of linting.

#3259 Also fix the component types, that may reveal actual typing errors in layout when using mypy.

**Comment by gvwilson** [comment]
@gothicVI please have a look at #3254 and let me know what you think?

**Comment by T4rk1n** [comment]
You need to build the components and run it from where it can find dash if running locally.

I get no more error when running this example.

**Comment by gothicVI** [comment]
@gvwilson Manjaro Linux

**Comment by gvwilson** [comment]
OK, I don't understand why that wouldn't work. Can you please check
out a fresh copy of the dash repo, go into it, and then run the
following and send me all the output? I'm greg.wilson@plot.ly.

$ npx lerna clean
$ rm -rf venv node_modules
$ python -m venv venv
$ . venv/bin/activate
$ pip install -e '.[dev,testing,ci]'  # note the quotes
$ nvm use lts/iron
$ npm i
$ npm run build
$ npm run setup-tests.py

**Comment by gothicVI** [comment]
@gvwilson here you go https://gist.github.com/gothicVI/8a8cb53ba0be2f060d30ebf004edbaeb
This fails at installing parts of the `ci` dependency due to python `3.13` not being supported...

I'll try and give it a shot with a machine running python `3.11` tomorrow.

**Comment by gothicVI** [comment]
hi @gvwilson the initial issue is not solved as you can see. All I solved was building dash using python `3.13`. Sure I can write a PR for that little change but you mentioned that the problem was solved on your side with the PR you wrote. I can not reproduce that. Please help me out and let me know what you did to make the suggested changes be compliant with my MWE. Thanks!

**Comment by gothicVI** [comment]
@gvwilson you had mentioned that with your patch you didn't see the issues. What exactly did you do?

**Comment by gvwilson** [comment]
hi @gothicVI - can you please re-try with the latest version of Dash?

**Comment by gothicVI** [comment]
Hi @gvwilson 
```
$ docker run -it --rm python:3.11-slim bash
root@c8109b30021c:/# python3 -m pip install dash mypy
root@c8109b30021c:/# python3 -m pip freeze
blinker==1.9.0
certifi==2025.4.26
charset-normalizer==3.4.2
click==8.1.8
dash==3.0.4
Flask==3.0.3
idna==3.10
importlib_metadata==8.7.0
itsdangerous==2.2.0
Jinja2==3.1.6
MarkupSafe==3.0.2
mypy==1.15.0
mypy_extensions==1.1.0
narwhals==1.38.0
nest-asyncio==1.6.0
packaging==25.0
plotly==6.0.1
requests==2.32.3
retrying==1.3.4
six==1.17.0
typing_extensions==4.13.2
urllib3==2.4.0
Werkzeug==3.0.6
zipp==3.21.0
root@c8109b30021c:/# cat t.py 
from dash import Dash, dcc, html
from dash.dependencies import Input, Output
from typing import Callable

app = Dash(__name__)

def create_layout() -> html.Div:
    return html.Div([
        dcc.Input(id='input-text', type='text', value='', placeholder='Enter text'),
        html.Div(id='output-text')
    ])  

app.layout = create_layout

@app.callback(Output('output-text', 'children'), Input('input-text', 'value'))
def update_output(value: str) -> str:
    return f'You entered: {value}'

if __name__ == '__main__':
    app.run(debug=True, port=9000)
root@c8109b30021c:/# mypy t.py 
Success: no issues found in 1 source file
```
this does look very promising! I'll give the changes in the last version a thorough look and will try to port our production code soon!

**Comment by gothicVI** [comment]
@gvwilson anything else I can provide or test?
I really think this is on a good track but some things are still failing and even introduced seemingly breaking changes.

**Comment by lycoming-engines** [comment]
We are having the same issue with pylance. Please update when you guys get to this fix.
