### ISSUE TITLE
Attribute Error when trying to import Dash

### ISSUE THREAD

**Issue by bcheung12345** [plotly/dash#129]
Hello,

I'm working with Python 3.4.5, using Anaconda 2.20 (64 bit). I'm working with the first dash example in the user guide (Dash Data Visualization). Within the Anaconda iPython instance, I have no problem importing the dash package, although the iPython instance just hangs without starting a page if I run the full example.

When I save the example into a python file and run from command prompt, I get the following error when trying to import dash:

C:\>python C:\app.py
Traceback (most recent call last):
  File "C:\app.py", line 2, in <module>
    import dash
  File "C:\dash.py", line 2, in <module>
    import dash_core_components as dcc
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\dash_core_components\__init__.py, line 8 in <module>
    _components = _dash.development.component_loader.load_components(
AttributeError: 'module' object has no attribute 'development'

Going into the specific module, it's complaining about this line and saying development doesn't exist:

_components = _dash.development.component_loader.load_components(
    _os.path.join(_current_path, 'metadata.json'),
    'dash_core_components'

Going back into the development folder in: C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\dash\, it clearly exists, and there is a component_loader.py file in there.

Question: Has anyone run into this problem before? It may not be a dash specific problem, but an import one.

**Comment by ned2** [comment]
It looks like you have created a file by the name of `dash.py` in the same directory as your `app.py` and this seems to be messing up the imports and being imported instead of the dash package. Remove or rename that file and it should all work.

**Comment by bcheung12345** [comment]
Yup. That solved it. 

Problem exists between keyboard and chair...

**Comment by ButeForce** [comment]
Dears I have similar issue , but I don't have any conflicts in the names of the files or folders , any help or recommendation is appreciate it, it worked once then stopped working

File "example1.py", line 1, in <module>
    import dash
  File "/var/www/dashproject/venv/lib/python3.5/site-packages/dash/__init__.py", line 1, in <module>
    from .dash import Dash  # noqa: F401
  File "/var/www/dashproject/venv/lib/python3.5/site-packages/dash/dash.py", line 9, in <module>
    from flask import Flask, Response
  File "/var/www/dashproject/venv/lib/python3.5/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/var/www/dashproject/venv/lib/python3.5/site-packages/werkzeug/__init__.py", line 151, in <module>
    __import__('werkzeug.exceptions')
  File "/var/www/dashproject/venv/lib/python3.5/site-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/var/www/dashproject/venv/lib/python3.5/site-packages/werkzeug/wrappers.py", line 27, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/var/www/dashproject/venv/lib/python3.5/site-packages/werkzeug/http.py", line 23, in <module>
    from email.utils import parsedate_tz
  File "/usr/lib/python3.5/email/utils.py", line 28, in <module>
    import random
  File "/var/www/dashproject/files/random.py", line 3, in <module>
    import dash_core_components as dcc
  File "/var/www/dashproject/venv/lib/python3.5/site-packages/dash_core_components/__init__.py", line 8, in <module>
    _components = _dash.development.component_loader.load_components(
AttributeError: module 'dash' has no attribute 'development'

**Comment by ned2** [comment]
Could you please post this question on the [Dash community forum](https://community.plot.ly/c/dash)? That's a better place for this kind of question, and you're more likely to get an answer there. (for this question it would probably be helpful to see your list of imports at the top of the file too)
