### ISSUE TITLE
cannot import name '_Wildcard' from 'dash.dependencies

### ISSUE THREAD

**Issue by doriankodelja-se** [plotly/dash#3580]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**

```
dash                        3.4.0
dash_ag_grid                31.3.1
dash-iconify                0.1.2
dash_mantine_components     2.4.1
dash-pydantic-form          0.18.2
dash-pydantic-utils         0.18.2
```

**Describe the bug**
Our app using dash used to work yesterday on 3.3.0 and fail after a new build on 3.4.0:

```
from dash_pydantic_form import ModelForm  

File "/usr/local/lib/python3.11/site-packages/dash_pydantic_form/__init__.py", line 6, in <module>  
from dash_pydantic_form.fields import fields  

File "/usr/local/lib/python3.11/site-packages/dash_pydantic_form/fields/__init__.py", line 11, in <module>  
from . import all_fields as fields  

File "/usr/local/lib/python3.11/site-packages/dash_pydantic_form/fields/all_fields.py", line 3, in <module>  
from .base_fields import AutocompleteField as Autocomplete  

File "/usr/local/lib/python3.11/site-packages/dash_pydantic_form/fields/base_fields.py", line 20, in <module>  
from dash_pydantic_form import ids as common_ids  

File "/usr/local/lib/python3.11/site-packages/dash_pydantic_form/ids.py", line 3, in <module>  
from dash.dependencies import _Wildcard  

ImportError: cannot import name '_Wildcard' from 'dash.dependencies' (/usr/local/lib/python3.11/site-packages/dash/dependencies.py)  
```

**Comment by T4rk1n** [comment]
The `_Wildcard` class has been renamed to simply `Wildcard`, would require to update dash_pydantic_form to use that instead as it was prefixed `_` not intended for external usage.

**Comment by T4rk1n** [comment]
Or add an alias for backward compatibility in here if anyone want to pick that up.

**Comment by Mr-Neutr0n** [comment]
Opened a PR for this: #3609
